# Generated by Django 3.2.3 on 2021-05-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresse_name', models.CharField(max_length=64, verbose_name='Addresse')),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=64)),
                ('shipping_add', models.BooleanField(default=False, help_text='Can this address be used as a shipping?', verbose_name='Shipping?')),
                ('billing_add', models.BooleanField(default=False, help_text='Can this addresed used as a billing address?', verbose_name='Billing?')),
                ('default_shipping', models.BooleanField(default=False, help_text='Is this the default shipping address?', verbose_name='Default Ship?')),
                ('default_billing', models.BooleanField(default=False, help_text='Is this the default billing address?', verbose_name='Default Bill?')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', related_query_name='address', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('category_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Listing Title')),
                ('short_desc', models.CharField(help_text='Short Description', max_length=64, verbose_name='Short Desc')),
                ('long_desc', models.TextField(help_text='Short Description', verbose_name='Long Desc')),
                ('startingprice', models.DecimalField(decimal_places=2, default=0.0, help_text='Startng bid price.', max_digits=10, verbose_name='Starting Price')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Creation Timestamp')),
                ('publish', models.BooleanField(default=False, help_text='Select to publish')),
                ('publish_ts', models.DateTimeField(default=None, verbose_name='Publish Timestamp')),
                ('closed', models.BooleanField(default=False, help_text='Close to accept highest bid.', verbose_name='Bidding Closed')),
                ('categories', models.ManyToManyField(blank=True, related_name='listings', to='auctions.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlistings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(help_text='Give a title to your comment.', max_length=64, verbose_name='Coment Title')),
                ('comment', models.TextField(help_text='Please enter your comments here.', verbose_name='Comment')),
                ('rating', models.IntegerField(help_text='Star Rating, 1 to 5 stars.', verbose_name='ratings')),
                ('commenting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', related_query_name='item_comments', to='auctions.listings', verbose_name='List Item')),
                ('commenting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', related_query_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidamt', models.DecimalField(decimal_places=2, default=0.0, help_text='What is your bid? Must be higher then the highest bid.', max_digits=10, verbose_name='Bib Price')),
                ('bid_ts', models.DateTimeField(auto_now_add=True, verbose_name='Bid Timestamp')),
                ('bid_accepted', models.BooleanField(default=False, help_text='This bid is accepted and bidding will close.', verbose_name='Bid Accpeted')),
                ('withdrawn', models.BooleanField(default=False, help_text='To withdraw your bid.', verbose_name='Withdrawan')),
                ('win_notify_add', models.EmailField(help_text='Email to notify win, if not provided, default profile email will be used.', max_length=254, verbose_name='Nofitcation Email')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddings', related_query_name='biddings', to=settings.AUTH_USER_MODEL, verbose_name='Bidding User')),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', related_query_name='bids', to='auctions.listings', verbose_name='List Item')),
                ('win_billing', models.ForeignKey(help_text='Billing Address to use, if bid wins.', on_delete=django.db.models.deletion.CASCADE, related_name='bid_billings', related_query_name='bid_billings', to='auctions.address', verbose_name='Billing Address')),
                ('win_shipping', models.ForeignKey(help_text='Shipping Address to use, if bid wins.', on_delete=django.db.models.deletion.CASCADE, related_name='bid_shippings', related_query_name='bid_shippings', to='auctions.address', verbose_name='Shipping Address')),
            ],
        ),
        migrations.AddIndex(
            model_name='listings',
            index=models.Index(fields=['title'], name='title.idx'),
        ),
        migrations.AddIndex(
            model_name='listings',
            index=models.Index(fields=['title', 'seller'], name='title_seller.idx'),
        ),
    ]
