# Generated by Django 3.2.3 on 2021-05-23 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210523_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='win_notify_add',
        ),
        migrations.AddField(
            model_name='bids',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='Email to notify win, if not provided, default profile email will be used.', max_length=254, verbose_name='Nofitcation Email'),
        ),
        migrations.AddField(
            model_name='listings',
            name='pic_url',
            field=models.URLField(default='file:///Users/Sekar/Django%20Projects/commerce/auctions/static/images/', help_text='Provide URL of where your pictures are.', verbose_name='Picture URL'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rate the Item, 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='ratings'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_ts', models.DateTimeField(auto_now_add=True, verbose_name='Watch Created Time')),
                ('suspend_watch', models.BooleanField(default=False, verbose_name='Suspended')),
                ('suspend_ts', models.DateTimeField(default=None, verbose_name='Suspend Time')),
                ('notify_email', models.EmailField(blank=True, help_text='Email to notify changes', max_length=254, verbose_name='Notify Email')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', related_query_name='watchlist', to='auctions.listings', verbose_name='Watch Item')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchings', related_query_name='watchings', to=settings.AUTH_USER_MODEL, verbose_name='Watcher')),
            ],
        ),
    ]
