# Generated by Django 3.2.3 on 2021-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210523_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='publish_ts',
            field=models.DateTimeField(default=None, null=True, verbose_name='Publish Timestamp'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='suspend_ts',
            field=models.DateTimeField(default=None, null=True, verbose_name='Suspend Time'),
        ),
    ]
