# Generated by Django 3.2.3 on 2021-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210524_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='publish_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish Timestamp'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='suspend_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspend Time'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='suspend_watch',
            field=models.BooleanField(default=False, verbose_name='Suspend Watch'),
        ),
    ]
