# Generated by Django 3.2.3 on 2021-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210524_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='pic_url',
            field=models.URLField(default='localhost:8800/images/0/blank.jpg', help_text='Provide URL of where your pictures are.', verbose_name='Picture URL'),
        ),
    ]
