# Generated by Django 3.2.3 on 2021-06-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210609_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='pic_upload',
            field=models.ImageField(default='http://127.0.0.1:8800/media/images/blank.jpg', help_text='Select a picture (*.jpg, *.gif, *.png) to upload', upload_to='images/', verbose_name='Upload Picture'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='pic_url',
            field=models.URLField(default='http://127.0.0.1:8800/media/images/blank.jpg', help_text='Provide URL of where your pictures are.', verbose_name='Picture URL'),
        ),
    ]
