# Generated by Django 3.2.3 on 2021-06-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210612_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='short_desc',
            field=models.CharField(help_text='Short Description', max_length=128, verbose_name='Short Desc'),
        ),
    ]
