# Generated by Django 3.2.3 on 2021-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comments_comment_ts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('item', 'watcher', 'suspend_ts'), name='item-watcher'),
        ),
    ]
