# Generated by Django 3.2.3 on 2021-06-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist_item-watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='win_billing',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='win_shipping',
        ),
    ]
