# Generated by Django 3.2.3 on 2021-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bids_bidamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidamt',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='What is your bid? Must be higher then the highest bid.', max_digits=10, verbose_name='Bib Price'),
        ),
    ]
