# Generated by Django 3.2.3 on 2021-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bids_bidamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='update_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Timestamp'),
        ),
    ]
