# Generated by Django 3.2.3 on 2021-07-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210705_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bill_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billings', related_query_name='billings', to='auctions.address', verbose_name='Bill To'),
        ),
        migrations.AddField(
            model_name='bids',
            name='ship_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shippings', related_query_name='shippings', to='auctions.address', verbose_name='Ship To'),
        ),
    ]
